FROM alpine:3.18

# Instalamos Java y Maven
RUN apk add --no-cache openjdk11 maven wget

WORKDIR /app
COPY service-corba/ ./service-corba/
COPY corba-bridge/ ./corba-bridge/

# Compilar e instalar el módulo común (Genera los Stubs con los nuevos campos)
RUN cd service-corba && mvn clean install -DskipTests

# Compilar y empaquetar el WAR del bridge
RUN cd corba-bridge && mvn clean package -DskipTests

# Descargamos e instalamos Tomcat 9 manualmente
RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz && \
    tar -xzf apache-tomcat-9.0.82.tar.gz && \
    mv apache-tomcat-9.0.82 /usr/local/tomcat && \
    rm apache-tomcat-9.0.82.tar.gz

# Limpiar aplicaciones y copiar nuestro WAR
RUN rm -rf /usr/local/tomcat/webapps/*
RUN cp corba-bridge/target/corba-bridge.war /usr/local/tomcat/webapps/corba-bridge.war

EXPOSE 8080

ENTRYPOINT ["/usr/local/tomcat/bin/catalina.sh", "run"]
