FROM alpine:3.18

# Instalamos Java y Maven directamente en Alpine
RUN apk add --no-cache openjdk11 maven

WORKDIR /app
COPY service-corba/ ./service-corba/

# Compilamos
RUN cd service-corba && mvn clean compile dependency:copy-dependencies -DoutputDirectory=target/dependency

# Comando de arranque
ENTRYPOINT ["java", "-cp", "service-corba/target/classes:service-corba/target/dependency/*", "com.futbol.server.BufferServer", "-ORBInitialPort", "1050", "-ORBInitialHost", "corba-naming"]
