sonar.exclusions=stencil-library/loader/**,stencil-library/dist/**,stencil-library/node_modules/**,**/node_modules/**
sonar.cpd.exclusions=**/*.spec.ts,**/*.cy.ts,**/*.spec.js,**/*.cy.js,**/player-detail/player-detail.page.html,**/player-detail-public/player-detail-public.page.html
