sonar.projectKey=football-frontend
sonar.organization=REPLACE_WITH_YOUR_SONARCLOUD_ORG
sonar.projectName=Football Frontend (Angular/Ionic)

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.cy.ts,**/node_modules/**,**/coverage/**,**/*.js.map
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.cy.ts

sonar.javascript.lcov.reportPaths=coverage/app/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
