module BufferApp {
    
    typedef sequence<string> TagList;

    struct NewsItem {
        string id;
        string title;     
        string author;
        string content;   
        string summary;
        string imageUrl;
        string category;
        TagList tags;     
        string date;      
        boolean isActive;
    };

    typedef sequence<NewsItem> NewsList;

    interface NewsService {
        // Métodos de Administración
        void addNews(in NewsItem noticia);
        boolean updateNews(in NewsItem noticia);
        boolean deleteNews(in string id);
        NewsList getAllNews();
        
        // Métodos de Usuario / Públicos
        NewsList getVisibleNews();
        NewsList getRecentNews();
        NewsItem getNewsById(in string id);
        
        oneway void shutdown();
    };
};
