openapi:
  title: Football Microservices System
  version: 1.0.0

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://football-eureka-server:8761/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.value}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

