openapi:
  title: Football - External Client API
  description: Microservicio Orquestador de Datos Externos
  version: 1.0.0
  contact:
    name: Alex Taquila Camasca
    email: atc757@inlumine.ual.es
    url: https://es.linkedin.com/in/alextaquilacamasca

server:
  port: 8085

spring:
  application:
    name: external-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

football:
  api:
    key: ${FOOTBALL_API_KEY}

tsdb:
  api:
    key: ${FOOTBALL_API_KEY}
    url: ${TSDB_BASE_URL:https://www.thesportsdb.com/api/v2/json}

google:
  api:
    key: ${GOOGLE_API_KEY}
    model: ${GEMINI_MODEL_JAVA:gemini-2.0-flash}
    version: ${GEMINI_API_VERSION_JAVA:v1}

logging:
  level:
    com.futbol.externalfeign.client: DEBUG

corba:
  bridge:
    url: "http://football-corba-bridge:8080/corba-bridge/api/noticias"
