openapi:
  title: Football - Player API
  description: Microservicio de gestión de jugadores
  version: 1.0.0
  contact:
    name: Alex Taquila Camasca
    email: atc757@inlumine.ual.es
    url: https://es.linkedin.com/in/alextaquilacamasca

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/football_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

info:
  application:
    name: ${spring.application.name}
    description: Microservicio de gestión de jugadores de fútbol
    version: 1.0.0