openapi:
  title: Football - Player Feign API
  description: Microservicio Orquestador de Jugadores
  version: 1.0.0
  contact:
    name: Alex Taquila Camasca
    email: atc757@inlumine.ual.es
    url: https://es.linkedin.com/in/alextaquilacamasca

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
