/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlayerCard {
        "age": number;
        "birthPlace": string;
        "firstname": string;
        "height": string;
        "lastname": string;
        "nationality": string;
        "number": number;
        "photo": string;
        "position": string;
        "weight": string;
    }
    interface PlayerList {
        /**
          * List of players as a JSON string
          * @default '[]'
         */
        "players": string;
        /**
          * Title of the widget
          * @default 'Mis Jugadores'
         */
        "widgetTitle": string;
    }
    interface TvScheduleWidget {
        /**
          * @default '[]'
         */
        "schedule": string;
        /**
          * @default 'Partidos de los próximos días'
         */
        "widgetTitle": string;
    }
}
export interface PlayerListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPlayerListElement;
}
declare global {
    interface HTMLPlayerCardElement extends Components.PlayerCard, HTMLStencilElement {
    }
    var HTMLPlayerCardElement: {
        prototype: HTMLPlayerCardElement;
        new (): HTMLPlayerCardElement;
    };
    interface HTMLPlayerListElementEventMap {
        "playerClicked": any;
        "viewMoreClicked": void;
    }
    interface HTMLPlayerListElement extends Components.PlayerList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPlayerListElementEventMap>(type: K, listener: (this: HTMLPlayerListElement, ev: PlayerListCustomEvent<HTMLPlayerListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPlayerListElementEventMap>(type: K, listener: (this: HTMLPlayerListElement, ev: PlayerListCustomEvent<HTMLPlayerListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPlayerListElement: {
        prototype: HTMLPlayerListElement;
        new (): HTMLPlayerListElement;
    };
    interface HTMLTvScheduleWidgetElement extends Components.TvScheduleWidget, HTMLStencilElement {
    }
    var HTMLTvScheduleWidgetElement: {
        prototype: HTMLTvScheduleWidgetElement;
        new (): HTMLTvScheduleWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "player-card": HTMLPlayerCardElement;
        "player-list": HTMLPlayerListElement;
        "tv-schedule-widget": HTMLTvScheduleWidgetElement;
    }
}
declare namespace LocalJSX {
    interface PlayerCard {
        "age"?: number;
        "birthPlace"?: string;
        "firstname"?: string;
        "height"?: string;
        "lastname"?: string;
        "nationality"?: string;
        "number"?: number;
        "photo"?: string;
        "position"?: string;
        "weight"?: string;
    }
    interface PlayerList {
        /**
          * Event emitted when a player is clicked
         */
        "onPlayerClicked"?: (event: PlayerListCustomEvent<any>) => void;
        /**
          * Event emitted when "Ver más" is clicked
         */
        "onViewMoreClicked"?: (event: PlayerListCustomEvent<void>) => void;
        /**
          * List of players as a JSON string
          * @default '[]'
         */
        "players"?: string;
        /**
          * Title of the widget
          * @default 'Mis Jugadores'
         */
        "widgetTitle"?: string;
    }
    interface TvScheduleWidget {
        /**
          * @default '[]'
         */
        "schedule"?: string;
        /**
          * @default 'Partidos de los próximos días'
         */
        "widgetTitle"?: string;
    }

    interface PlayerCardAttributes {
        "firstname": string;
        "lastname": string;
        "photo": string;
        "age": number;
        "nationality": string;
        "height": string;
        "weight": string;
        "number": number;
        "position": string;
        "birthPlace": string;
    }
    interface PlayerListAttributes {
        "players": string;
        "widgetTitle": string;
    }
    interface TvScheduleWidgetAttributes {
        "schedule": string;
        "widgetTitle": string;
    }

    interface IntrinsicElements {
        "player-card": Omit<PlayerCard, keyof PlayerCardAttributes> & { [K in keyof PlayerCard & keyof PlayerCardAttributes]?: PlayerCard[K] } & { [K in keyof PlayerCard & keyof PlayerCardAttributes as `attr:${K}`]?: PlayerCardAttributes[K] } & { [K in keyof PlayerCard & keyof PlayerCardAttributes as `prop:${K}`]?: PlayerCard[K] };
        "player-list": Omit<PlayerList, keyof PlayerListAttributes> & { [K in keyof PlayerList & keyof PlayerListAttributes]?: PlayerList[K] } & { [K in keyof PlayerList & keyof PlayerListAttributes as `attr:${K}`]?: PlayerListAttributes[K] } & { [K in keyof PlayerList & keyof PlayerListAttributes as `prop:${K}`]?: PlayerList[K] };
        "tv-schedule-widget": Omit<TvScheduleWidget, keyof TvScheduleWidgetAttributes> & { [K in keyof TvScheduleWidget & keyof TvScheduleWidgetAttributes]?: TvScheduleWidget[K] } & { [K in keyof TvScheduleWidget & keyof TvScheduleWidgetAttributes as `attr:${K}`]?: TvScheduleWidgetAttributes[K] } & { [K in keyof TvScheduleWidget & keyof TvScheduleWidgetAttributes as `prop:${K}`]?: TvScheduleWidget[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "player-card": LocalJSX.IntrinsicElements["player-card"] & JSXBase.HTMLAttributes<HTMLPlayerCardElement>;
            "player-list": LocalJSX.IntrinsicElements["player-list"] & JSXBase.HTMLAttributes<HTMLPlayerListElement>;
            "tv-schedule-widget": LocalJSX.IntrinsicElements["tv-schedule-widget"] & JSXBase.HTMLAttributes<HTMLTvScheduleWidgetElement>;
        }
    }
}
